# Generated by Django 3.0.3 on 2020-04-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200422_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AIRecruiterUser',
            new_name='AIUser',
        ),
    ]
